### ISSUE TITLE
Unable to launch starter project on M1 mac due to cocoapods build failure

### ISSUE THREAD

**Issue by BlkPingu** [kodecocodes/video-fda-materials#1]
Please advise.

```
Launching lib/main.dart on macOS in debug mode...
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Finding Podfile changes
      A desktop_window
      R sqlite3_flutter_libs
      - FlutterMacOS
      - path_provider_foundation
    Fetching external sources
    -> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral`
    -> Fetching podspec for `desktop_window` from `Flutter/ephemeral/.symlinks/plugins/desktop_window/macos`
    -> Fetching podspec for `path_provider_foundation` from `Flutter/ephemeral/.symlinks/plugins/path_provider_foundation/macos`
    Resolving dependencies of `Podfile`
Error output from CocoaPods:
↳
    Ignoring json-2.1.0 because its extensions are not built. Try: gem pristine json --version 2.1.0
    Ignoring bcrypt-3.1.12 because its extensions are not built. Try: gem pristine bcrypt --version 3.1.12
    Ignoring bindex-0.5.0 because its extensions are not built. Try: gem pristine bindex --version 0.5.0
    Ignoring binding_of_caller-0.8.0 because its extensions are not built. Try: gem pristine binding_of_caller --version 0.8.0
    Ignoring bootsnap-1.3.1 because its extensions are not built. Try: gem pristine bootsnap --version 1.3.1
    Ignoring bootsnap-1.3.0 because its extensions are not built. Try: gem pristine bootsnap --version 1.3.0
    Ignoring byebug-10.0.2 because its extensions are not built. Try: gem pristine byebug --version 10.0.2
    Ignoring debug_inspector-0.0.3 because its extensions are not built. Try: gem pristine debug_inspector --version 0.0.3
    Ignoring executable-hooks-1.4.2 because its extensions are not built. Try: gem pristine executable-hooks --version 1.4.2
    Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
    Ignoring ffi-1.9.24 because its extensions are not built. Try: gem pristine ffi --version 1.9.24
    Ignoring ffi-1.9.23 because its extensions are not built. Try: gem pristine ffi --version 1.9.23
    Ignoring gem-wrappers-1.3.2 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.3.2
    Ignoring json-2.1.0 because its extensions are not built. Try: gem pristine json --version 2.1.0
    Ignoring msgpack-1.2.4 because its extensions are not built. Try: gem pristine msgpack --version 1.2.4
    Ignoring nio4r-2.3.1 because its extensions are not built. Try: gem pristine nio4r --version 2.3.1
    Ignoring nio4r-2.3.0 because its extensions are not built. Try: gem pristine nio4r --version 2.3.0
    Ignoring nokogiri-1.8.4 because its extensions are not built. Try: gem pristine nokogiri --version 1.8.4
    Ignoring nokogiri-1.8.2 because its extensions are not built. Try: gem pristine nokogiri --version 1.8.2
    Ignoring pg-1.1.2 because its extensions are not built. Try: gem pristine pg --version 1.1.2
    Ignoring psych-3.0.2 because its extensions are not built. Try: gem pristine psych --version 3.0.2
    Ignoring puma-3.12.0 because its extensions are not built. Try: gem pristine puma --version 3.12.0
    Ignoring puma-3.11.4 because its extensions are not built. Try: gem pristine puma --version 3.11.4
    Ignoring rainbow-2.2.2 because its extensions are not built. Try: gem pristine rainbow --version 2.2.2
    Ignoring scrypt-3.0.5 because its extensions are not built. Try: gem pristine scrypt --version 3.0.5
    Ignoring sqlite3-1.3.13 because its extensions are not built. Try: gem pristine sqlite3 --version 1.3.13
    Ignoring websocket-driver-0.7.0 because its extensions are not built. Try: gem pristine websocket-driver --version 0.7.0
    Ignoring websocket-driver-0.6.5 because its extensions are not built. Try: gem pristine websocket-driver --version 0.6.5
    /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/mime-types-3.2.2/lib/mime/types.rb:69: warning: already initialized constant MIME::Types::VERSION
    /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/mime-types-3.2.2/lib/mime/types.rb:69: warning: previous definition of VERSION was here
    <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': --> /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/mime-types-3.2.2/lib/mime/types/logger.rb
    _1 is reserved for numbered parameter_2 is reserved for numbered parameter_3 is reserved for numbered parameter
       8  module MIME
      10    class Types
      17      class WarnLogger < ::Logger #:nodoc:
    > 30        def initialize(_1, _2 = nil, _3 = nil)
    > 34        end
      35      end
      38    end
      39  end
    /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: _1 is reserved for numbered parameter (SyntaxError)
    /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: _2 is reserved for numbered parameter
    /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: _3 is reserved for numbered parameter
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/mime-types-3.2.2/lib/mime/types.rb:228:in `<top (required)>'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/mime-types-3.2.2/lib/mime/types/columnar.rb:3:in `<top (required)>'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/ethon-0.16.0/lib/ethon.rb:6:in `<top (required)>'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:53:in `refresh_metadata'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source.rb:31:in `initialize'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:30:in `initialize'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:315:in `new'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:315:in `block in source_from_path'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:322:in `source_from_path'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:331:in `block in aggregate_with_repos'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:331:in `map'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:331:in `aggregate_with_repos'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:26:in `aggregate'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:60:in `all'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/user_interface/error_report.rb:173:in `repo_information'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/user_interface/error_report.rb:77:in `stack'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/user_interface/error_report.rb:24:in `report'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/command.rb:66:in `report_error'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/claide-1.1.0/lib/claide/command.rb:396:in `handle_exception'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/claide-1.1.0/lib/claide/command.rb:337:in `rescue in run'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/claide-1.1.0/lib/claide/command.rb:324:in `run'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/command.rb:52:in `run'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/bin/pod:55:in `<top (required)>'
    	from /opt/homebrew/Cellar/cocoapods/1.12.0/libexec/bin/pod:25:in `load'
    	from /opt/homebrew/Cellar/cocoapods/1.12.0/libexec/bin/pod:25:in `<main>'
    <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': --> /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/mime-types-3.2.2/lib/mime/types/logger.rb
    _1 is reserved for numbered parameter_2 is reserved for numbered parameter_3 is reserved for numbered parameter
       8  module MIME
      10    class Types
      17      class WarnLogger < ::Logger #:nodoc:
    > 30        def initialize(_1, _2 = nil, _3 = nil)
    > 34        end
      35      end
      38    end
      39  end
    /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: _1 is reserved for numbered parameter (SyntaxError)
    /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: _2 is reserved for numbered parameter
    /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: _3 is reserved for numbered parameter
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/mime-types-3.2.2/lib/mime/types.rb:228:in `<top (required)>'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/mime-types-3.2.2/lib/mime/types/columnar.rb:3:in `<top (required)>'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:159:in `require'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:159:in `rescue in require'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:39:in `require'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/ethon-0.16.0/lib/ethon.rb:6:in `<top (required)>'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:53:in `refresh_metadata'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source.rb:31:in `initialize'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:30:in `initialize'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:315:in `new'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:315:in `block in source_from_path'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:322:in `source_from_path'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:331:in `block in aggregate_with_repos'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:331:in `map'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:331:in `aggregate_with_repos'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:26:in `aggregate'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:60:in `all'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:393:in `source_with_url'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/sources_manager.rb:22:in `find_or_create_source_with_url'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:179:in `block in sources'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:178:in `map'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:178:in `sources'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:1081:in `block in resolve_dependencies'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/user_interface.rb:64:in `section'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:422:in `analyze'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/user_interface.rb:64:in `section'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:162:in `install!'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/command/install.rb:52:in `run'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/command.rb:52:in `run'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/bin/pod:55:in `<top (required)>'
    	from /opt/homebrew/Cellar/cocoapods/1.12.0/libexec/bin/pod:25:in `load'
    	from /opt/homebrew/Cellar/cocoapods/1.12.0/libexec/bin/pod:25:in `<main>'
    <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- mime/types/columnar (LoadError)
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/ethon-0.16.0/lib/ethon.rb:6:in `<top (required)>'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:53:in `refresh_metadata'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source.rb:31:in `initialize'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:30:in `initialize'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:315:in `new'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:315:in `block in source_from_path'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:322:in `source_from_path'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:331:in `block in aggregate_with_repos'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:331:in `map'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:331:in `aggregate_with_repos'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:26:in `aggregate'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:60:in `all'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source/manager.rb:393:in `source_with_url'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/sources_manager.rb:22:in `find_or_create_source_with_url'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:179:in `block in sources'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:178:in `map'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:178:in `sources'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:1081:in `block in resolve_dependencies'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/user_interface.rb:64:in `section'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:422:in `analyze'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/user_interface.rb:64:in `section'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:162:in `install!'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/command/install.rb:52:in `run'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/lib/cocoapods/command.rb:52:in `run'
    	from /Users/Tobias/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.12.0/bin/pod:55:in `<top (required)>'
    	from /opt/homebrew/Cellar/cocoapods/1.12.0/libexec/bin/pod:25:in `load'
    	from /opt/homebrew/Cellar/cocoapods/1.12.0/libexec/bin/pod:25:in `<main>'
Exception: Error running pod install
Exited

```

**Comment by kevindmoore** [comment]
I would try this first. From the command line inside of the project type:
flutter clean
flutter pub get

and then try. Otherwise it looks like you have multiple versions of ruby running. From homebrew you have ruby 3.2.2 and I see a ruby-2.4.1

**Comment by BlkPingu** [comment]
That worked, thanks! Took me a while to clean up, but rvm, rbenv and home-brew rubies were all used to compile different things and that's why nothing worked. It does now.

### For others finding this: 

- check `gem env` for inconsistencies in PATH and env.
- `which -a ruby` to find out where rubies are installed
- `ruby -v` to find out which ruby is used. It should show the same ruby as `rbenv versions`. Otherwise, check path and set global ruby.
- It's advisable to have only one ruby version manager installed and not to use system ruby. 

- If you want to set `rbenv global 3.1.0` after installing it (`rbenv install 3.1.0 --verbose`) for example and use it to compile cocoapods, make sure rbenv is in the PATH by appending to the end of your `.bash_profile` or `.zshrc`

    ```
    export PATH="$HOME/.rbenv/bin:$PATH" 
    eval "$(rbenv init -)"
   ```

[this page](https://mac.install.guide/faq/check-ruby-version/index.html) will help you debug.

good luck and feel free to mention @ me if you need help with cocoapods and other build issues.
